"""Add firewallListState table for hash-based list tracking.

Revision ID: 0009_firewall_list_state
Revises: 0008_fw_addr_state
Create Date: 2026-04-13 04:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0009_firewall_list_state'
down_revision = '0008_fw_addr_state'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'firewallListState',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('createDate', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updateDate', sa.DateTime(timezone=True), nullable=False),
        sa.Column('flagInactive', sa.SmallInteger(), nullable=False, server_default='0'),
        sa.Column('firewallsId', sa.BigInteger(), nullable=False),
        sa.Column('listName', sa.Text(), nullable=False),
        sa.Column('contentHash', sa.Text(), nullable=False),
        sa.Column('entryCount', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('lastPushedAt', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['firewallsId'], ['iplist.firewalls.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('firewallsId', 'listName', name='ux_firewallListState_firewall_listname'),
        schema='iplist'
    )
    op.create_index('ix_firewallListState_flagInactive', 'firewallListState', ['flagInactive'], schema='iplist')
    op.create_index('ix_firewallListState_firewallsId', 'firewallListState', ['firewallsId'], schema='iplist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_firewallListState_firewallsId', table_name='firewallListState', schema='iplist')
    op.drop_index('ix_firewallListState_flagInactive', table_name='firewallListState', schema='iplist')
    op.drop_table('firewallListState', schema='iplist')
    # ### end Alembic commands ###
